import axios from 'axios';

const baseUrl = 'http://localhost:8081/examenes';

export const listarExamenesPendientesService = {
    getExamenesPendientes: async () => {
        try {
            const response = await axios.get(`${baseUrl}/listar-pendientes`, {
                withCredentials: true
            });
            return response.data;
        } catch (error) {
            console.error('Error al obtener los ex치menes pendientes:', error);
            throw error;
        }
    },

};

export const pacientesConExamenService = {
    getPacientesConExamen: async () => {
        try {
            const response = await axios.get(`${baseUrl}/pacientes-con-examen`, {
                withCredentials: true
            });
            return response.data;
        } catch (error) {
            console.error('Error al obtener los pacientes con ex치menes:', error);
            throw error;
        }
    },
};

export const historialExamenesPorPacienteService = {
    getHistorialExamenesPorPaciente: async (id_paciente) => {
        try {
            const response = await axios.get(`${baseUrl}/historial/${id_paciente}`, {
                withCredentials: true
            });
            return response.data;
        } catch (error) {
            console.error('Error al obtener el historial de ex치menes por paciente:', error);
            throw error;
        }
    },
};


export const mostrarResultadosExamenService = {
    getResultadosExamen: async (id_examen) => {
        try {
            const response = await axios.get(`${baseUrl}/resultados/${id_examen}`, {
                withCredentials: true
            });
            return response.data;
        } catch (error) {
            console.error('Error al obtener los resultados del examen:', error);
            throw error;
        }
    },
};

export const listarExamenesCompletadosService = {
    getExamenesCompletados: async () => {
        try {
            const response = await axios.get(`${baseUrl}/listar-completados`, {
                withCredentials: true
            });
            return response.data;
        } catch (error) {
            console.error('Error al obtener los ex치menes completados:', error);
            throw error;
        }
    },
};